name: Auto Build and Publish

on:
  schedule: # run automatically, generally they update on tuesday to thursday, so i think run every friday noon is best
    # if you want set other time can use this website: http://cron.ciding.cc/
    - cron: '0 12 * * 5' # run every week Friday at 12:00 UTC
  workflow_dispatch: # allow run by manual command

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUBLISH_TOKEN }}
        
    - name: Setup Parameters
      run: |
        # setup your parameter here
        echo "BASE_REPOSITORY=https://github.com/LSPosed/MagiskOnWSALocal.git" >> $GITHUB_ENV
        echo "RELEASE_REPOSITORY=Nacho-Neko/MagiskOnWSAOnlineBuild" >> $GITHUB_ENV
        echo "PARAMETER="--arch arm64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --magisk-ver stable --compress-format zip"" >> $GITHUB_ENV

    - name: Install Git
      run: sudo apt-get install git
    
    - name: Setup GitHub CLI
      run: |
        # install last CLI
        version=$(curl --silent "https://api.github.com/repos/cli/cli/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
        version=${version#v} 
        curl -sSL "https://github.com/cli/cli/releases/download/v${version}/gh_${version}_linux_amd64.tar.gz" -o gh.tar.gz
        tar xzf gh.tar.gz
        sudo install gh*/bin/gh /usr/local/bin

    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.PUBLISH_TOKEN }}" | gh auth login --with-token

    - name: Clone repository
      run: git clone ${{ env.BASE_REPOSITORY }} MagiskOnWSALocal

    - name: Install dependencies
      run: |
        cd MagiskOnWSALocal
        # Run install_deps.sh script (depend on they request)
        chmod +x scripts/install_deps.sh
        ./scripts/install_deps.sh

    - name: Build
      run: |
        cd MagiskOnWSALocal
        chmod +x ./scripts/build.sh
        echo "BUILD_TIMESTAMP=$(date -u +"%Y-%m-%d %T")" >> $GITHUB_ENV
        echo "BUILD_UNIX_TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
        ./scripts/build.sh ${{ env.PARAMETER }}
      
    - name: Publish new release
      run: |
        cd MagiskOnWSALocal/output
        FILE=$(ls *.zip)
        NAME=$(echo $FILE | cut -d '_' -f -2)

        # Upload limit, '(' ')' will use '.' install
        CFILE=$(echo $FILE | sed 's/(/./g; s/)/./g')
        
        # List all release tags
        ALL_RELEASES=$(gh release list -R ${{ env.RELEASE_REPOSITORY }} | awk '{print $1}')
        
        # if version is exist, it will skip.
        if [[ -z $(echo "$ALL_RELEASES" | grep "$NAME") ]]
        then
          gh release create "$NAME" $FILE -R ${{ env.RELEASE_REPOSITORY }} -t "Magisk_On_$NAME" -n ""
        else
          echo "The version has not changed, skipping the release."
        fi
          
